apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zgmq502vi-nodejs
  janus-idp.io/tekton: zgmq502vi-nodejs
  backstage.io/kubernetes-id: zgmq502vi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zgmq502vi-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
